"""add mpesa and flutterwave fields to purchase orders

Revision ID: 40be7af007e9
Revises: 45526633e300
Create Date: 2026-09-02 11:09:06.316949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40be7af007e9'
down_revision = '45526633e300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mpesa_merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_result_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('flw_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('flw_charge_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('flw_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('flw_redirect_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('flw_status_detail', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_orders_flw_charge_id'), ['flw_charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_mpesa_checkout_request_id'), ['mpesa_checkout_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_mpesa_checkout_request_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_flw_charge_id'))
        batch_op.drop_column('flw_status_detail')
        batch_op.drop_column('flw_redirect_url')
        batch_op.drop_column('flw_reference')
        batch_op.drop_column('flw_charge_id')
        batch_op.drop_column('flw_customer_id')
        batch_op.drop_column('mpesa_result_desc')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('mpesa_checkout_request_id')
        batch_op.drop_column('mpesa_merchant_request_id')
        batch_op.drop_column('mpesa_phone_number')

    # ### end Alembic commands ###
